apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: roboshop
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    app: payment
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      app: payment
      tier: app
  template:
    metadata:
      labels:
        project: roboshop
        app: payment
        tier: app
    spec:
      containers:
      - name: payment
        image: rakeshn88/payment:v1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: payment

---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    project: roboshop
    app: payment
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
