apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    app: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabel:
      project: roboshop
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        app: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: rakeshn88/mongodb:v1
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    project: roboshop
    app: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017